### ISSUE TITLE
Warning at OSH Park

### ISSUE THREAD

**Issue by lpla** [rebbTRSi/synccross-LSDj-1-to-3-adapter-#1]
Hello rebb. I just entered the GB chiptune world and this item is perfect for my purposes as I don't want to, probably, break my DMG-07 (as I saw that happened to some people in chiptune.org).

Then, I saw that you don't have any stock for the synccross, but the PCB is uploaded here. So, I tried to do a OSH Park order with it but this warning appears:

<img width="1324" alt="image" src="https://user-images.githubusercontent.com/1533393/45325267-c2804f00-b550-11e8-94fc-2f9afa4318b6.png">

I know that it is not critical but I have really no idea about PCB design, only programming. Do you know how to fix that?

Also, just one more question. Are you going to sell/release a new version or redesign soon? I read something about DMG cable and analog sync options, but I don't really need any of that, but if any redesign replaces this one it would be nice to know before I place the order to Europe.

Thanks in advance!

**Comment by rebbTRSi** [comment]
Their validation routine just don't understand design that have no components. Program sees just pads without silkscreen (Usually used to mark component placements in design) on bottom layer. You can safely ignore this warning.

**Comment by lpla** [comment]
Oh, okay. Nice to know. But before I close this issue, any news about a redesign? Just before I make a order (from you if you have any unit left or from OSH Park directly)

**Comment by rebbTRSi** [comment]
I've learnt not give any estimates when i don't have one. I want to re-design it to be more multipurpose and i need one with analog sync myself. But cannot really give any timeframe for now. 
Only have one left for myself atm, so safe to order from OSH park.

**Comment by lpla** [comment]
Nice! That's all I wanted to know. Thanks for your answers and sharing these models!

Closing issue now.
